import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

console.log("EXAMPLE_ENV: ", process.env.EXAMPLE_ENV);

const Home: NextPage = () => {
  const [greet, setGreet] = useState("");
  const [date, setDate] = useState("");

  const onClickButtonA = async () => {
    try {
      const res = await fetch("/api/hello"); // Returns 404 page!
      const data = await res.json(); // Cannot parse as JSON because `res` is 404 page.
      setGreet(data.name);
      return;
    } catch (e) {
      console.error("Error in requesting Next API", e);
    }
  };

  const onClickButtonB = async () => {
    try {
      const res = await fetch("/api/date");
      const data = await res.json();
      setDate(data.date);
    } catch (e) {
      console.error("Error in requesting Python API", e);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <button className={styles.button} onClick={() => onClickButtonA()}>
          Fetch data from Next API
        </button>

        <p>Greet: {greet}</p>

        <button className={styles.button} onClick={() => onClickButtonB()}>
          Fetch data from Python API
        </button>

        <p>Date: {date}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
